### PR TITLE
Overclock

### PR DESCRIPTION
**Pull request by ghost**
Added CONFIG_MSM8960_CPU_OVERCLOCK
Bus is 533MHz
Minimum CPU frequency reduced to 192MHz
max. CPU frequencies are 2000MHz @ 1.3V for nominal and fast PVS, 1900MHz @ 1.35V for slow PVS
- CPU voltages are a continuation based on stock values
- slow pvs is one big screwup to overclock:
  qualcomm never used anything higher that 1.3V; custom kernels can be seen to use up to 1.35V

### CODE REVIEW

**Comment by ghost** [comment]
Nominal seems stable enough. On my cpu vmin is applied so most freqs are 1150mV.
I have no way to test fast and, espacially, slow PVS binns. Not sure if slow is actually safe to push that much.

**Comment by SkrilaxCZ** [comment]
I have two questions:
1) Why is minimal CPU frequency 192 MHz? For such change we would need to compare stats (time spent in 384 MHz with time spent in 192 MHz). Standard way for non-interactive tasks (i.e those for 384 / 192 MHz is to put the frequency higher in order to run the CPU for a short time).
2) How well is the 2 GHz tested? Was thermald settings adapted to 2 GHz?

**Comment by dhacker29** [comment]
I have been running 2ghz since pushed with no issues and no thermald changes

**Comment by ghost** [comment]
Good point, there is no good reason for 192MHz. My device is spending a lot of time on 192 (on an avg. 20x more vs. 384) but with the given voltage there is no good reason to keep it, quite the oposite, it can only hurt battery life. I was not thinking about that.

As for 2GHz - I've been testing (with and without patched thermal) on common usage (browsing, calls, mms...) and benchmarks. I've tried my best to overload the device and it remained stable. Been watching logcat for thermal changes and, even though there were a lot of them, it never shutted down, rebooted or even reached temp higher than 65 celsius with thermald conf 1900000 1800000 1728000 1512000 1350000 486000 384000 5000 (no changes to temperature tresholds).

But slow pvs is bothering me. QC never excedeed 1300mV. At least I didn't find any mention of it. And my CPU PVS is nominal so I can't test.

**Comment by SkrilaxCZ** [comment]
@dhacker29 Unpatched thermald confix will soon cause max, frequency to be set back to 1.5 GHz.

**Comment by ghost** [comment]
Is it OK if this request is closed and a new one created instead? I screwed up by not basing this on a clean branch and now I can't simply modifiy the pull request (remove the 192MHz step).

**Pull request closed without merging**
