### PR TITLE
Allow changing voltage via sysfs

### PR DESCRIPTION
**Pull request by ghost**
Adds sysfs UV_mV_table

Thanks to imoseyon

### CODE REVIEW

**Comment by SkrilaxCZ** [comment]
So this is for things like SetCPU? Tested & Working?

**Comment by ghost** [comment]
Yes. It was working the last time I tested. My device has vmin applied so I abandoned it along the way (also was too lazy to play with it). But I can readd and retest if needed.

**Comment by ghost** [comment]
Probaly would need to clean up as well. I assume those new commits were added upon reopening (originally, it was only one commit)

**Comment by ghost** [comment]
It is working.
Apps that can be used to tweak voltage (eg. setcpu) permit range from 600mV to 1.6V. I tried to set 384MHzon 600mV but it was reset to 800mV. Which is correct. This patch would need to be fixed to use HFPLL_LOW_VDD instead of hardcoding the value and do similar for max voltage.

**Comment by ghost** [comment]
Is there something wrong with this? I'd really like to know what I screwed up.
Thank you in advance ;)

**Comment by SkrilaxCZ** [comment]
I understood the previous comment as there is still something to fix. Anyway:

1) do not use "ssize_t" for the voltage, you can't return "-1" that way
2) Do not link via "extern" etc., use the ops for the driver, this would become mess too soon. Add new ops to the cpufreq driver.

**Comment by ghost** [comment]
OK. I'm new to this so please don't scream at me.

1) Are you sure about ssize_t ? I'm not sure if it's any different in current kernel but:

> ... size_t where the parameter specifies the length of an object to manipulate, and return the portion of the length of the object processed in a type ssize_t. The type ssize_t is required so that a negative return value can be used to indicate an error... So you should use size_t whenever you mean to return a size in bytes, and ssize_t whenever you would return either a size in bytes or a (negative) error value.

It seems common to use ssize_t for size of sysfs objects in current cpufreq driver.
Nevertheless, what would you recomend instead of ssize_t?

2) what is "ops"? (new) option, feature?

I'll play with this some more. But I can't promise I'll succeed.

**Comment by ghost** [comment]
Abandoned

**Comment by SkrilaxCZ** [comment]
1) Well it's actually signed size_t, but I still would use int. size_t is used for size of something.

2) "ops" is the structure with operations between cpufreq and it's driver for the platform. Add two new ops there (= function pointers) for the voltage and modify the cpufreq driver for msm8960 to include your funcitons.

**Pull request closed without merging**
