### PR TITLE
Build fix.

### PR DESCRIPTION
**Pull request by skeevy420**
Fixes kernel not compiling due do the build environment being dirty.  I got tired of having to run make mrproper after every repo sync.

### CODE REVIEW

**Comment by skeevy420** [comment]
Ignore this, only meant to pull request the ran make mrproper.  Didn't mean to add in the crap I was messing with.

**Comment by epinter** [comment]
Change on the default i/o scheduler caused boot problems in the past.
Overclock causes instability and doubts.
I never needed to run mrproper...

**Comment by skeevy420** [comment]
I've had to run mrproper from the git go.  Only way I could get CM10.1 to compile following the instructions provided here.
Overclock has been stable since I've been using it.  I'm using values provided in the source for the 3 ramped up states.  Set voltage according to the pattern the other states were using. 
Haven't tested anything "update defconfig; ..."  and up since I'm getting a build error from the kernel missing include/sound/compress_params.h because https://github.com/CyanogenMod/android_hardware_qcom_audio-caf/blob/cm-10.1/libalsa-intf/alsa_pcm.c needs it.

**Comment by dhacker29** [comment]
The fix for that was merged into hardware/com/audio-caf earlier

**Comment by skeevy420** [comment]
I saw that, and that you did it.  Thank you for that.  Also pretty cool that a fellow Arky provided the fix.

**Pull request closed without merging**
